# Generated by Django 4.0.4 on 2022-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Location', models.CharField(max_length=60)),
                ('Date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Events List',
            },
        ),
    ]
