# Generated by Django 4.0.4 on 2022-04-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='Events',
        ),
    ]
